/*TMODJS:{"version":1,"md5":"f121b99365e56054d10905e83be7d2c1"}*/
template('profile/password',function($data,$filename
/**/) {
'use strict';var $utils=this,$helpers=$utils.$helpers,include=function(filename,data){data=data||$data;var text=$utils.$include(filename,data,$filename);$out+=text;return $out;},$escape=$utils.$escape,lang=$data.lang,$out='';$out+='<div class="container"> ';
include('../public/breadcrumbs');
$out+=' <div class="card"> <div class="card-header"> <h2>修改密码</h2> </div> <div class="card-body card-padding"> <form class="form-horizontal form-validate" action="_data/error.json" role="form"> <div class="form-group"> <label for="oldPwd" class="col-sm-2 control-label">原密码</label> <div class="col-sm-10"> <div class="fg-line"> <input type="password" class="form-control input-sm validate[required]" id="oldPwd" name="oldPwd" placeholder="原密码"> </div> <small class="help-block">&nbsp;</small> </div> </div> <div class="form-group"> <label for="newPwd" class="col-sm-2 control-label">新密码</label> <div class="col-sm-10"> <div class="fg-line"> <input type="password" class="form-control input-sm validate[required]" id="newPwd" name="newPwd" placeholder="新密码"> </div> <small class="help-block">&nbsp;</small> </div> </div> <div class="form-group"> <label for="rePwd" class="col-sm-2 control-label">确认密码</label> <div class="col-sm-10"> <div class="fg-line"> <input type="password" class="form-control input-sm validate[equals[newPwd]]" id="rePwd" name="rePwd" placeholder="确认密码"> </div> <small class="help-block">&nbsp;</small> </div> </div> <div class="form-group"> <div class="col-sm-offset-2 col-sm-10"> <button type="button" class="btn btn-primary btn-sm btn-save">';
$out+=$escape(lang.btn.save);
$out+='</button> </div> </div> </form> </div> </div> </div>';
return new String($out);
});