/*TMODJS:{"version":2,"md5":"5f2679a0f84e3c506ee0c57b0489f8c0"}*/
template('search/index',function($data,$filename
/**/) {
'use strict';var $utils=this,$helpers=$utils.$helpers,include=function(filename,data){data=data||$data;var text=$utils.$include(filename,data,$filename);$out+=text;return $out;},$escape=$utils.$escape,query=$data.query,lang=$data.lang,$each=$utils.$each,list=$data.list,$value=$data.$value,$index=$data.$index,$string=$utils.$string,pagination=$data.pagination,$out='';$out+='<div class="container"> ';
include('../public/breadcrumbs');
$out+=' <div class="card"> <div class="card-header"> <h2>查询DEMO</h2> <ul class="actions"> <li> <a href="#_data/search/new.json?tpl=search/editM" class="btn-modal"> <i class="zmdi zmdi-plus"></i> </a> </li> <li> <a href="#" class="upload-xsl"> <i class="zmdi zmdi-upload"></i> <input class="hidden" type="file" data-url="_data/error.json" name="files[]" multiple> </a> </li> <li> <a href="#" class="btn-export" data-url="_data/export/data.json" data-form-id="frmSearch"> <i class="zmdi zmdi-download"></i> </a> </li> </ul> </div> <div class="bootgrid-header container-fluid"> <form id="frmSearch" action="#_data/search/index.json?tpl=search/index" role="form"> <div class="row"> <div class="col-sm-10"> <div class="input-group"> <span class="input-group-addon"><i class="zmdi zmdi-search"></i></span> <div class="fg-line"> <input type="text" class="form-control auto-complete" name="txtMain" data-url="_data/typeahead/all.json" value="';
$out+=$escape(query.txtMain);
$out+='" placeholder="主要查询条件(自动完成)"> </div> </div> </div> <div class="col-sm-2"> <button type="button" class="btn btn-primary btn-sm m-t-5 waves-effect btn-search"> ';
$out+=$escape(lang.btn.search);
$out+=' </button> </div> </div> <div class="row"> <div class="col-sm-4"> <div class="input-group"> <span class="input-group-addon"><i class="zmdi zmdi-search"></i></span> <div class="fg-line"> <input type="text" class="form-control auto-select" name="txtSelect" data-url="_data/typeahead/all.json" value="';
$out+=$escape(query.txtSelect);
$out+='" data-text="';
$out+=$escape(query.txtSelectText);
$out+='" placeholder="自动完成(只能选择)"> </div> </div> </div> </div> <div class="row"> <div class="col-sm-4"> <div class="input-group"> <span class="input-group-addon"><i class="zmdi zmdi-search"></i></span> <div class="fg-line"> <select class="select-picker" name="selNormal" data-value="';
$out+=$escape(query.selNormal);
$out+='"> <option value="">常规</option> <option>重庆</option> <option>北京</option> <option>天津</option> <option>上海</option> </select> </div> </div> </div> <div class="col-sm-4"> <div class="input-group"> <span class="input-group-addon"><i class="zmdi zmdi-search"></i></span> <div class="fg-line"> <select class="select-picker" name="selSearch" data-value="';
$out+=$escape(query.selSearch);
$out+='" data-live-search="true"> <option value="">可查询</option> <option>重庆</option> <option>北京</option> <option>天津</option> <option>上海</option> </select> </div> </div> </div> <div class="col-sm-4"> <div class="input-group"> <span class="input-group-addon"><i class="zmdi zmdi-search"></i></span> <div class="fg-line"> <select class="select-picker" name="selGroup" data-value="';
$out+=$escape(query.selGroup);
$out+='" data-live-search="true"> <option value="">分组选择</option> <optgroup label="直辖市"> <option>重庆</option> <option>北京</option> <option>天津</option> <option>上海</option> </optgroup> <optgroup label="河北省"> <option>石家庄</option> <option>唐山</option> <option>保定</option> </optgroup> </select> </div> </div> </div> </div> <div class="row"> <div class="col-sm-3"> <div class="input-group form-group"> <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span> <div class="dtp-container fg-line"> <input type=\'text\' class="form-control date-picker" name="dateBegin" value="';
$out+=$escape(query.dateBegin);
$out+='" placeholder="';
$out+=$escape(lang.search.dateBegin);
$out+='"> </div> </div> </div> <div class="col-sm-3"> <div class="input-group form-group"> <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span> <div class="dtp-container fg-line"> <input type=\'text\' class="form-control date-picker" name="dateEnd" value="';
$out+=$escape(query.dateEnd);
$out+='" placeholder="';
$out+=$escape(lang.search.dateEnd);
$out+='"> </div> </div> </div> <div class="col-sm-6"> <div class="input-group form-group"> <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span> <div class="dtp-container fg-line"> <input type=\'text\' class="form-control daterange-picker" name="daterange" value="';
$out+=$escape(query.daterange);
$out+='" placeholder="';
$out+=$escape(lang.search.daterange);
$out+='"> </div> </div> </div> </div> <div class="row"> <div class="col-sm-3"> <div class="input-group form-group"> <span class="input-group-addon"><i class="zmdi zmdi-calendar"></i></span> <div class="dtp-container fg-line"> <input type=\'text\' class="form-control date-time-picker" name="datetime" value="';
$out+=$escape(query.datetime);
$out+='" placeholder="可以选择时间"> </div> </div> </div> </div> </form> </div> <div class="table-responsive"> <table class="table table-striped table-hover"> <thead> <tr> <th>#</th> <th>First Name</th> <th>Last Name</th> <th>Username</th> <th>Nickname</th> <th>DateTime</th> <th>操作</th> </tr> </thead> <tbody> ';
$each(list,function($value,$index){
$out+=' <tr> <td>';
$out+=$escape($index+1);
$out+='</td> <td>';
$out+=$escape($value.firstName);
$out+='</td> <td>';
$out+=$escape($value.lastName);
$out+='</td> <td>';
$out+=$escape($value.userName);
$out+='</td> <td>';
$out+=$escape($value.nickName);
$out+='</td> <td>';
$out+=$escape($helpers. dateFormat($value.DateTime ));
$out+='</td> <td> <button type="button" class="btn btn-xs btn-default btn-icon btn-modal" data-size="modal-lg" data-href="#_data/search/edit.json?tpl=search/editM&id=';
$out+=$escape($index);
$out+='"> <span class="zmdi zmdi-edit"></span> </button> <button type="button" class="btn btn-xs btn-danger btn-icon btn-del" data-id="';
$out+=$escape($index);
$out+='" data-url="_data/error.json"> <span class="zmdi zmdi-delete"></span> </button> </td> </tr> ';
});
$out+=' </tbody> </table> </div> ';
$out+=$string(pagination);
$out+=' </div> </div>';
return new String($out);
});